name: Build Flet Windows EXE

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: '程序名称'
        required: true
        default: 'HelloFlet'
      icon_path:
        description: '图标路径'
        required: true
        default: 'assets/icon.ico'
  push:
    tags: [ "v*" ]

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flet

      - name: Cache Flet build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~\.flet\cache
            ~\AppData\Local\Temp\flet-*
          key: flet-cache-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Build EXE with Flet pack
        # 使用PowerShell兼容的语法，用反引号`作为换行符
        run: |
          flet pack main.py `
            --name "${{ github.event.inputs.app_name }}" `
            --icon "${{ github.event.inputs.icon_path }}" `
            --output "dist"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}-windows
          path: dist\${{ github.event.inputs.app_name }}.exe

      - name: Create GitHub Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist\${{ github.event.inputs.app_name }}.exe
          name: Release ${{ github.ref_name }}
