name: build-apk
on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          packages: platform-tools build-tools;34.0.0 platforms;android-34

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: stable
          cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install flet==0.28.3

      - run: yes | flutter doctor --android-licenses || true

      - name: Add execute permission to gradlew (if exists)
        run: |
          if [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          else
            echo "android/gradlew not found, skipping..."
          fi
        shell: bash

      - run: flet build apk --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: HelloFlet-Android
          path: build/app/outputs/flutter-apk/release.apk
