name: Build Windows EXE

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: '程序名称'
        required: true
        default: 'HelloFlet'
      icon_path:
        description: '图标路径'
        required: true
        default: 'assets/icon.ico'
  push:
    tags: [ "v*" ]

jobs:
  windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python & cache pip
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Cache PyInstaller build cache
        uses: actions/cache@v4
        with:
          path: |
            ~\AppData\Local\pyinstaller\bincache*
            ~\AppData\Local\pyinstaller\Cache
          key: pyinstaller-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Build EXE
        run: |
          pyinstaller -F -w main.py --name ${{ github.event.inputs.app_name }} --icon ${{ github.event.inputs.icon_path }}

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name }}-Windows
          path: dist/${{ github.event.inputs.app_name }}.exe
