name: build-exe
on:
  workflow_dispatch:
  push:
    tags: ["v*"]
jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller -F -w main.py --name HelloFlet
      - uses: actions/upload-artifact@v4
        with:
          name: HelloFlet-Windows
          path: dist/HelloFlet.exe
