name: build-apk
on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 官方 action 会一次性装好 Flutter + Android SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: stable
          cache: false
          android: true            # 关键：让 action 自带 cmdline-tools
          setup-android-sdk: true  # 关键：让 action 自动装 platform-tools / build-tools

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install flet==0.28.3

      # 自动接受许可证
      - run: yes | flutter doctor --android-licenses || true

      # 构建
      - run: flet build apk --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: HelloFlet-Android
          path: build/app/outputs/apk/release/app-release.apk
