android-apk:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter & cache SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.19"
        channel: stable
        cache: true

    - name: Setup Python & cache pip
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install Flet
      run: pip install flet

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build APK
      run: flet build apk --verbose

    - name: Find APK
      id: find_apk
      run: |
        apk_path=$(find build -name "*.apk" -type f | head -n 1)
        echo "APK_PATH=$apk_path" >> $GITHUB_OUTPUT
        echo "Detected APK at: $apk_path"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: HelloFlet-Android
        path: ${{ steps.find_apk.outputs.APK_PATH }}
