name: build-apk
on:
  workflow_dispatch:
  push:
    tags: ["v*"]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: {distribution: "temurin", java-version: 17}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: stable
          cache: true

      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}

      - run: pip install flet==0.28.3

      - name: Setup Android toolchain
        run: |
          flutter config --no-analytics
          flutter doctor
          yes | flutter doctor --android-licenses || true

      - run: flet build apk --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: HelloFlet-Android
          path: build/app/outputs/apk/release/app-release.apk
