name: build-apk
on:
  # 手动触发：Actions → build-apk → Run workflow
  workflow_dispatch:
  # 打 tag 触发：git tag v1.x && git push origin v1.x
  push:
    tags: ["v*"]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    # 国内镜像；海外可删掉
    env:
      PUB_HOSTED_URL: https://pub.flutter-io.cn 
      FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn 

    steps:
      # 1) 拉代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Java 17（Flutter 3.24 必需）
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3) Flutter 3.24.5（关闭缓存避免拉成 3.29）
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: stable
          cache: false

      # 4) Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 5) 装 Flet 0.28.3
      - name: Install Flet
        run: pip install flet==0.28.3

      # 6) 接受 Android 许可证
      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      # 7) 预装 Android SDK 组件（NDK、build-tools、platform）
      - name: Install Android SDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;26.3.11579264"
        env:
          ANDROID_HOME: ${{ steps.flutter-action.outputs.ANDROID_HOME }}

      # 8) 构建 APK（verbose 方便调试）
      - name: Build APK
        run: flet build apk --verbose

      # 9) 上传产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HelloFlet-Android
          path: build/app/outputs/apk/release/app-release.apk
          if-no-files-found: error
