name: build-apk
on:
  workflow_dispatch:          # 手动触发
  push:
    tags: ["v*"]              # 打 tag 触发

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Flutter 3.24.5 + Android SDK (含 cmdline-tools)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5"
          channel: stable
          cache: false
          android: true        # 自动装 cmdline-tools

      # 4. Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 5. 安装 Flet 0.28.3
      - name: Install Flet
        run: pip install flet==0.28.3

      # 6. 接受 Android 许可证
      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      # 7. 预装 SDK 组件（NDK 26.3.11579264 对应 Flutter 3.24）
      - name: Install Android SDK components
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;26.3.11579264"

      # 8. 构建 APK
      - name: Build APK
        run: flet build apk --verbose

      # 9. 上传产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HelloFlet-Android
          path: build/app/outputs/apk/release/app-release.apk
